/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeSessionIdRouteImport } from './routes/practice.$sessionId'
import { Route as LessonSubtopicIdRouteImport } from './routes/lesson.$subtopicId'
import { Route as PracticeSessionIdReviewRouteImport } from './routes/practice.$sessionId.review'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSessionIdRoute = PracticeSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => PracticeRoute,
} as any)
const LessonSubtopicIdRoute = LessonSubtopicIdRouteImport.update({
  id: '/lesson/$subtopicId',
  path: '/lesson/$subtopicId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSessionIdReviewRoute = PracticeSessionIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PracticeSessionIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/syllabus': typeof SyllabusRoute
  '/today': typeof TodayRoute
  '/lesson/$subtopicId': typeof LessonSubtopicIdRoute
  '/practice/$sessionId': typeof PracticeSessionIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/practice/$sessionId/review': typeof PracticeSessionIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/syllabus': typeof SyllabusRoute
  '/today': typeof TodayRoute
  '/lesson/$subtopicId': typeof LessonSubtopicIdRoute
  '/practice/$sessionId': typeof PracticeSessionIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/practice/$sessionId/review': typeof PracticeSessionIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/dashboard': typeof DashboardRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/syllabus': typeof SyllabusRoute
  '/today': typeof TodayRoute
  '/lesson/$subtopicId': typeof LessonSubtopicIdRoute
  '/practice/$sessionId': typeof PracticeSessionIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/practice/$sessionId/review': typeof PracticeSessionIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/dashboard'
    | '/diagnostic'
    | '/login'
    | '/practice'
    | '/progress'
    | '/syllabus'
    | '/today'
    | '/lesson/$subtopicId'
    | '/practice/$sessionId'
    | '/api/auth/$'
    | '/practice/$sessionId/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/dashboard'
    | '/diagnostic'
    | '/login'
    | '/practice'
    | '/progress'
    | '/syllabus'
    | '/today'
    | '/lesson/$subtopicId'
    | '/practice/$sessionId'
    | '/api/auth/$'
    | '/practice/$sessionId/review'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/dashboard'
    | '/diagnostic'
    | '/login'
    | '/practice'
    | '/progress'
    | '/syllabus'
    | '/today'
    | '/lesson/$subtopicId'
    | '/practice/$sessionId'
    | '/api/auth/$'
    | '/practice/$sessionId/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosticRoute: typeof DiagnosticRoute
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  SyllabusRoute: typeof SyllabusRoute
  TodayRoute: typeof TodayRoute
  LessonSubtopicIdRoute: typeof LessonSubtopicIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$sessionId': {
      id: '/practice/$sessionId'
      path: '/$sessionId'
      fullPath: '/practice/$sessionId'
      preLoaderRoute: typeof PracticeSessionIdRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/lesson/$subtopicId': {
      id: '/lesson/$subtopicId'
      path: '/lesson/$subtopicId'
      fullPath: '/lesson/$subtopicId'
      preLoaderRoute: typeof LessonSubtopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$sessionId/review': {
      id: '/practice/$sessionId/review'
      path: '/review'
      fullPath: '/practice/$sessionId/review'
      preLoaderRoute: typeof PracticeSessionIdReviewRouteImport
      parentRoute: typeof PracticeSessionIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PracticeSessionIdRouteChildren {
  PracticeSessionIdReviewRoute: typeof PracticeSessionIdReviewRoute
}

const PracticeSessionIdRouteChildren: PracticeSessionIdRouteChildren = {
  PracticeSessionIdReviewRoute: PracticeSessionIdReviewRoute,
}

const PracticeSessionIdRouteWithChildren =
  PracticeSessionIdRoute._addFileChildren(PracticeSessionIdRouteChildren)

interface PracticeRouteChildren {
  PracticeSessionIdRoute: typeof PracticeSessionIdRouteWithChildren
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeSessionIdRoute: PracticeSessionIdRouteWithChildren,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  DashboardRoute: DashboardRoute,
  DiagnosticRoute: DiagnosticRoute,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRouteWithChildren,
  ProgressRoute: ProgressRoute,
  SyllabusRoute: SyllabusRoute,
  TodayRoute: TodayRoute,
  LessonSubtopicIdRoute: LessonSubtopicIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
