/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadPdfsRouteImport } from './routes/upload-pdfs'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as IndexRouteImport } from './routes/index'

const UploadPdfsRoute = UploadPdfsRouteImport.update({
  id: '/upload-pdfs',
  path: '/upload-pdfs',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/progress': typeof ProgressRoute
  '/questions': typeof QuestionsRoute
  '/upload-pdfs': typeof UploadPdfsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/progress': typeof ProgressRoute
  '/questions': typeof QuestionsRoute
  '/upload-pdfs': typeof UploadPdfsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/progress': typeof ProgressRoute
  '/questions': typeof QuestionsRoute
  '/upload-pdfs': typeof UploadPdfsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diagnostic' | '/progress' | '/questions' | '/upload-pdfs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diagnostic' | '/progress' | '/questions' | '/upload-pdfs'
  id:
    | '__root__'
    | '/'
    | '/diagnostic'
    | '/progress'
    | '/questions'
    | '/upload-pdfs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticRoute: typeof DiagnosticRoute
  ProgressRoute: typeof ProgressRoute
  QuestionsRoute: typeof QuestionsRoute
  UploadPdfsRoute: typeof UploadPdfsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-pdfs': {
      id: '/upload-pdfs'
      path: '/upload-pdfs'
      fullPath: '/upload-pdfs'
      preLoaderRoute: typeof UploadPdfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticRoute: DiagnosticRoute,
  ProgressRoute: ProgressRoute,
  QuestionsRoute: QuestionsRoute,
  UploadPdfsRoute: UploadPdfsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
